var old_ha = draw_get_halign()
var old_va = draw_get_valign()
var old_color = draw_get_color()
var old_alpha = draw_get_alpha()
draw_set_halign(fa_center)
draw_set_valign(fa_top)
draw_set_color(c_white)
draw_set_alpha(1.0)
draw_text(x, text_y, credits_text)
draw_set_color(c_green)
draw_set_alpha(rect_alpha)
draw_rectangle(0, 0, 640, 480, false)
draw_set_color(old_color)
draw_set_halign(old_ha)
draw_set_valign(old_va)
draw_set_alpha(old_alpha)