name: Nightly build

on:
  push:
    branches: [ "godot" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build exports
        run: bash exports/actions_build.sh

      - name: Upload Windows x86_64 export
        uses: actions/upload-artifact@v4
        with:
          name: windows.x86_64
          path: exports/SECRET.windows.x86_64.exe

      - name: Upload Windows Arm export
        uses: actions/upload-artifact@v4
        with:
          name: windows.arm
          path: exports/SECRET.windows.arm.exe

      - name: Upload Linux x86_64 export
        uses: actions/upload-artifact@v4
        with:
          name: linux.x86_64
          path: exports/SECRET.linux.x86_64

      - name: Upload Linux Arm export
        uses: actions/upload-artifact@v4
        with:
          name: linux.arm
          path: exports/SECRET.linux.arm

      - name: Upload macOS export
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: exports/SECRET.macos.zip
          
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload web export
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'exports/web/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
